### ISSUE TITLE
Bug: conflicts are not handled properly

### ISSUE THREAD

**Issue by corollari** [paulrberg/multisol#8]
If somewhere in the import path there are two contracts with the same name only one of the contracts will get pulled, meaning that imports that relied on the other contract will break.

## Steps to reproduce
Let's say you have the following import tree (A->B means "A imports B"):
A->B
B->"openzeppelin-solidity/contracts/utils/Address.sol"
A->"@openzeppelin/contracts/utils/Address.sol"

Then you are importing different versions of the contract `Address.sol` through different contracts, and what happens when multisol is run is that only one (let's say "openzeppelin-solidity/contracts/utils/Address.sol") will get picked, making the compiler throw an error because of the incompatibility.

## Test case
```
git clone https://github.com/keep-community/redemption-bounties
cd contracts
multisol contracts/Collateral.sol
```

## Proposed solutions
1. Warn the user that a conflict was found
2. Automatically change the name of the contracts to solve conflicts

The second solution might be too much work but implementing the 1st should be pretty easy and it will already help a lot.

**Comment by PaulRBerg** [comment]
Fixed in [v1.0.2](https://github.com/paulrberg/multisol/releases/tag/v1.0.2).
